#------------------------------------------------
# server:
#------------------------------------------------

# sda
- platform: mqtt
  state_topic: "sys/server/hw/storage/sda/state"
  name: "server_sda_mqtt_state"

- platform: mqtt
  state_topic: "sys/server/hw/storage/sda/state"
  json_attributes_topic: "sys/server/hw/storage/sda"
  name: "server_sda"

# model/SN
- platform: mqtt
  state_topic: "sys/server/hw/storage/sda"
  json_attributes_topic: "sys/server/hw/storage/sda"
  name: "server: sda model"
  value_template: "{{ value_json.model }}"

- platform: mqtt
  state_topic: "sys/server/hw/storage/sda/temperature"
  name: "server: sda temperature"
#  friendly_name: >-
#    sda
#    {{ states( 'sensor.server_sda_model' ) }}
  unit_of_measurement: '°C'
  device_class: temperature

- platform: template
  sensors:
    server_sda_state:
      friendly_name: "server: sda state"
      value_template: >-
        {{ states( 'sensor.server_sda_mqtt_state' ) }}
        {% if states( 'sensor.server_sd_freshness' ) != "OK" %}
          (?!)
        {% endif %}

# sdb
- platform: mqtt
  state_topic: "sys/server/hw/storage/sdb/state"
  name: "server_sdb_mqtt_state"

# model/SN
- platform: mqtt
  state_topic: "sys/server/hw/storage/sdb"
  json_attributes_topic: "sys/server/hw/storage/sdb"
  name: "server: sdb model"
  value_template: "{{ value_json.model }}"

- platform: mqtt
  state_topic: "sys/server/hw/storage/sdb/temperature"
  name: "server: sdb temperature"
  unit_of_measurement: '°C'
  device_class: temperature

- platform: template
  sensors:
    server_sdb_state:
      friendly_name: "server: sdb state"
      value_template: >-
        {{ states( 'sensor.server_sdb_mqtt_state' ) }}
        {% if states( 'sensor.server_sd_freshness' ) != "OK" %}
          (?!)
        {% endif %}

# sdc
- platform: mqtt
  state_topic: "sys/server/hw/storage/sdc/state"
  name: "server_sdc_mqtt_state"

# model/SN
- platform: mqtt
  state_topic: "sys/server/hw/storage/sdc"
  json_attributes_topic: "sys/server/hw/storage/sdc"
  name: "server: sdc model"
  value_template: "{{ value_json.model }}"

- platform: mqtt
  state_topic: "sys/server/hw/storage/sdc/temperature"
  name: "server: sdc temperature"
  unit_of_measurement: '°C'
  device_class: temperature

- platform: template
  sensors:
    server_sdc_state:
      friendly_name: "server: sdc state"
      value_template: >-
        {{ states( 'sensor.server_sdc_mqtt_state' ) }}
        {% if states( 'sensor.server_sd_freshness' ) != "OK" %}
          (?!)
        {% endif %}

# sdd
- platform: mqtt
  state_topic: "sys/server/hw/storage/sdd/state"
  name: "server_sdd_mqtt_state"

# model/SN
- platform: mqtt
  state_topic: "sys/server/hw/storage/sdd"
  json_attributes_topic: "sys/server/hw/storage/sdd"
  name: "server: sdd model"
  value_template: "{{ value_json.model }}"

- platform: mqtt
  state_topic: "sys/server/hw/storage/sdd/temperature"
  name: "server: sdd temperature"
  unit_of_measurement: '°C'
  device_class: temperature

- platform: template
  sensors:
    server_sdd_state:
      friendly_name: "server: sdd state"
      value_template: >-
        {{ states( 'sensor.server_sdd_mqtt_state' ) }}
        {% if states( 'sensor.server_sd_freshness' ) != "OK" %}
          (?!)
        {% endif %}

# sde
- platform: mqtt
  state_topic: "sys/server/hw/storage/sde/state"
  name: "server_sde_mqtt_state"

# model/SN
- platform: mqtt
  state_topic: "sys/server/hw/storage/sde"
  json_attributes_topic: "sys/server/hw/storage/sde"
  name: "server: sde model"
  value_template: "{{ value_json.model }}"

- platform: mqtt
  state_topic: "sys/server/hw/storage/sde/temperature"
  name: "server: sde temperature"
  unit_of_measurement: '°C'
  device_class: temperature

- platform: template
  sensors:
    server_sde_state:
      friendly_name: "server: sde state"
      value_template: >-
        {{ states( 'sensor.server_sde_mqtt_state' ) }}
        {% if states( 'sensor.server_sd_freshness' ) != "OK" %}
          (?!)
        {% endif %}

# sdX data freshness
- platform: mqtt
  state_topic: "sys/server/hw/storage/sda/updated"
  json_attributes_topic: "sys/server/hw/storage/sda/updated"
  name: "server: sda last update"
  device_class: timestamp
  value_template: "{{ value_json.timestamp }}"

- platform: template
  sensors:
    server_sd_freshness:
      friendly_name: "server: sd(a) data freshness check"
      value_template: >-
        {% set topic_u = 'sensor.server_sda_last_update' %}
        {% if as_timestamp(now()) - ( states( topic_u )|float ) > 1800 %}
          OLD: {{ state_attr( topic_u, 'date' ) }}
        {% else %}
          OK
        {% endif %}
      icon_template: >-
        {% set topic_u = 'sensor.server_sda_last_update' %}
        {% if as_timestamp(now()) - ( states( topic_u )|float ) > 1800 %}
          mdi:disc-alert
        {% else %}
          mdi:harddisk
        {% endif %}

